# Generated by Django 4.0.5 on 2022-07-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=120, unique=True, verbose_name='option key unique')),
                ('option_value', models.TextField(blank=True, null=True, verbose_name='option value')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('private', models.BooleanField(null=True, verbose_name='private value')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'remotes_options',
                'managed': True,
            },
        ),
    ]
