# Generated by Django 4.0.5 on 2022-07-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerlButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dom', models.CharField(max_length=50)),
                ('gate', models.CharField(max_length=50)),
                ('mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerlCameras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dvr', models.SmallIntegerField()),
                ('cam', models.SmallIntegerField()),
            ],
        ),
    ]
