# Generated by Django 4.0.5 on 2022-07-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0002_perlbuttons_perlcameras'),
    ]

    operations = [
        migrations.AddField(
            model_name='perlbuttons',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perlcameras',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
