# Generated by Django 4.0.5 on 2022-07-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0004_alter_perlbuttons_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perlcameras',
            name='type',
            field=models.CharField(default='home', max_length=255),
            preserve_default=False,
        ),
    ]
