# Generated by Django 4.0.5 on 2022-07-04 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remotes', '0006_perlcameras_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perlcameras',
            name='button',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remotes.perlbuttons'),
        ),
    ]
